#生产环境
server:
  servlet:
    path: /api/v1
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-2d1zll67.gz.tencentcdb.com:10025/app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gy123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true